### ISSUE TITLE
CTR Button doesn't respond to scroll

### ISSUE THREAD

**Issue by choyiny** [FGMEMBERS/747-8i#1]
CTR button does not respond to scrolling, and only accepts left click, and goes one way. So there's no way to make the screen APP :(

**Comment by dogsaysmoo** [comment]
The CTR button isn't supposed to change the mode.  It changes the view angle.  Try the knob.

**Comment by CA1012** [comment]
A few days ago I experienced the same problem. I fixed that by downloading
the latest version of the plane. Hope this helps.
